version: '3.7'

services:
  chatroom:
    build: .
    command: npm start
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - CACHE_URL=redis://redis:6379
      - DB_URL=mongodb://mongo:27017/chatroomsdb
      - SESSION_SECRET=topSecret
      - PORT=3000
    depends_on:
      - redis
      - mongo
    container_name: backend
  redis:
    image: redis
    container_name: cache
    restart: unless-stopped
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=chatroomsdb
    container_name: db
    restart: unless-stopped