FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

ARG CACHE_URL
ARG CACHE_PORT
ARG CACHE_USERNAME
ARG CACHE_PASSWORD
ARG PORT
ARG STAGE
ARG SESSION_SECRET
ARG DB_URL

ENV CACHE_URL ${CACHE_URL}
ENV CACHE_PORT ${CACHE_PORT}
ENV CACHE_USERNAME ${CACHE_USERNAME}
ENV CACHE_PASSWORD ${CACHE_PASSWORD}
ENV PORT ${PORT}
ENV STAGE ${STAGE}
ENV SESSION_SECRET ${SESSION_SECRET}
ENV DB_URL ${DB_URL}

COPY . .

ENTRYPOINT [ "npm", "run", "dev" ]
